def getComponentIndexes(model,c_source):
    pos[0] = np.where(model[rxnNames] == c_source)
    pos[1] = np.where(model[rxnNames] == 'L-alanine exchange')
    pos[2] = np.where(model[rxnNames] == 'L-arginine exchange')
    pos[3] = np.where(model[rxnNames] == 'L-asparagine exchange')
    pos[4] = np.where(model[rxnNames] == 'L-aspartate exchange')
    pos[5] = np.where(model[rxnNames] == 'L-cysteine exchange')
    pos[6] = np.where(model[rxnNames] == 'L-glutamine exchange')
    pos[7] = np.where(model[rxnNames] == 'L-glutamate exchange')
    pos[8] = np.where(model[rxnNames] == 'L-glycine exchange')
    pos[9] = np.where(model[rxnNames] == 'L-histidine exchange')
    pos[10] = np.where(model[rxnNames] == 'L-isoleucine exchange')
    pos[11] = np.where(model[rxnNames] == 'L-leucine exchange')
    pos[12] = np.where(model[rxnNames] == 'L-lysine exchange')
    pos[13] = np.where(model[rxnNames] == 'L-methionine exchange')
    pos[14] = np.where(model[rxnNames] == 'L-phenylalanine exchange')
    pos[15] = np.where(model[rxnNames] == 'L-proline exchange')
    pos[16] = np.where(model[rxnNames] == 'L-serine exchange')
    pos[17] = np.where(model[rxnNames] == 'L-threonine exchange')
    pos[18] = np.where(model[rxnNames] == 'L-tryptophan exchange')
    pos[19] = np.where(model[rxnNames] == 'L-tyrosine exchange')
    pos[20] = np.where(model[rxnNames] == 'L-valine exchange')
    pos[21] = np.where(model[rxnNames] == '2''-deoxyadenosine exchange')
    pos[22] = np.where(model[rxnNames] == '2''-deoxyguanosine exchange')
    pos[23] = np.where(model[rxnNames] == 'thymidine exchange')
    pos[24] = np.where(model[rxnNames] == 'deoxycytidine exchange')
    pos[25] = np.where(model[rxnNames] == 'D-glucose exchange')